/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ApiPublicActionSourceStatutRouteImport } from './routes/api/public/action-source-statut'
import { Route as ApiPublicActionSourceSuivanteRouteImport } from './routes/api/public/action-source-suivante'
import { Route as ApiPublicDemandeStatutRouteImport } from './routes/api/public/demande-statut'
import { Route as ApiPublicDemandesSuivanteRouteImport } from './routes/api/public/demandes-suivante'
import { Route as ApiPublicListerAbonnesRouteImport } from './routes/api/public/lister-abonnes'
import { Route as ApiPublicNettoyageStatutRouteImport } from './routes/api/public/nettoyage-statut'
import { Route as ApiPublicNettoyageSuivantRouteImport } from './routes/api/public/nettoyage-suivant'
import { Route as ApiPublicPublierSourcesRouteImport } from './routes/api/public/publier-sources'
import { Route as ApiPublicPublierSyntheseRouteImport } from './routes/api/public/publier-synthese'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicActionSourceStatutRoute =
  ApiPublicActionSourceStatutRouteImport.update({
    id: '/api/public/action-source-statut',
    path: '/api/public/action-source-statut',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActionSourceSuivanteRoute =
  ApiPublicActionSourceSuivanteRouteImport.update({
    id: '/api/public/action-source-suivante',
    path: '/api/public/action-source-suivante',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDemandeStatutRoute = ApiPublicDemandeStatutRouteImport.update({
  id: '/api/public/demande-statut',
  path: '/api/public/demande-statut',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemandesSuivanteRoute =
  ApiPublicDemandesSuivanteRouteImport.update({
    id: '/api/public/demandes-suivante',
    path: '/api/public/demandes-suivante',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicListerAbonnesRoute = ApiPublicListerAbonnesRouteImport.update({
  id: '/api/public/lister-abonnes',
  path: '/api/public/lister-abonnes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNettoyageStatutRoute =
  ApiPublicNettoyageStatutRouteImport.update({
    id: '/api/public/nettoyage-statut',
    path: '/api/public/nettoyage-statut',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNettoyageSuivantRoute =
  ApiPublicNettoyageSuivantRouteImport.update({
    id: '/api/public/nettoyage-suivant',
    path: '/api/public/nettoyage-suivant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPublierSourcesRoute = ApiPublicPublierSourcesRouteImport.update({
  id: '/api/public/publier-sources',
  path: '/api/public/publier-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublierSyntheseRoute =
  ApiPublicPublierSyntheseRouteImport.update({
    id: '/api/public/publier-synthese',
    path: '/api/public/publier-synthese',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compte': typeof CompteRoute
  '/api/public/action-source-statut': typeof ApiPublicActionSourceStatutRoute
  '/api/public/action-source-suivante': typeof ApiPublicActionSourceSuivanteRoute
  '/api/public/demande-statut': typeof ApiPublicDemandeStatutRoute
  '/api/public/demandes-suivante': typeof ApiPublicDemandesSuivanteRoute
  '/api/public/lister-abonnes': typeof ApiPublicListerAbonnesRoute
  '/api/public/nettoyage-statut': typeof ApiPublicNettoyageStatutRoute
  '/api/public/nettoyage-suivant': typeof ApiPublicNettoyageSuivantRoute
  '/api/public/publier-sources': typeof ApiPublicPublierSourcesRoute
  '/api/public/publier-synthese': typeof ApiPublicPublierSyntheseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compte': typeof CompteRoute
  '/api/public/action-source-statut': typeof ApiPublicActionSourceStatutRoute
  '/api/public/action-source-suivante': typeof ApiPublicActionSourceSuivanteRoute
  '/api/public/demande-statut': typeof ApiPublicDemandeStatutRoute
  '/api/public/demandes-suivante': typeof ApiPublicDemandesSuivanteRoute
  '/api/public/lister-abonnes': typeof ApiPublicListerAbonnesRoute
  '/api/public/nettoyage-statut': typeof ApiPublicNettoyageStatutRoute
  '/api/public/nettoyage-suivant': typeof ApiPublicNettoyageSuivantRoute
  '/api/public/publier-sources': typeof ApiPublicPublierSourcesRoute
  '/api/public/publier-synthese': typeof ApiPublicPublierSyntheseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compte': typeof CompteRoute
  '/api/public/action-source-statut': typeof ApiPublicActionSourceStatutRoute
  '/api/public/action-source-suivante': typeof ApiPublicActionSourceSuivanteRoute
  '/api/public/demande-statut': typeof ApiPublicDemandeStatutRoute
  '/api/public/demandes-suivante': typeof ApiPublicDemandesSuivanteRoute
  '/api/public/lister-abonnes': typeof ApiPublicListerAbonnesRoute
  '/api/public/nettoyage-statut': typeof ApiPublicNettoyageStatutRoute
  '/api/public/nettoyage-suivant': typeof ApiPublicNettoyageSuivantRoute
  '/api/public/publier-sources': typeof ApiPublicPublierSourcesRoute
  '/api/public/publier-synthese': typeof ApiPublicPublierSyntheseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compte'
    | '/api/public/action-source-statut'
    | '/api/public/action-source-suivante'
    | '/api/public/demande-statut'
    | '/api/public/demandes-suivante'
    | '/api/public/lister-abonnes'
    | '/api/public/nettoyage-statut'
    | '/api/public/nettoyage-suivant'
    | '/api/public/publier-sources'
    | '/api/public/publier-synthese'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compte'
    | '/api/public/action-source-statut'
    | '/api/public/action-source-suivante'
    | '/api/public/demande-statut'
    | '/api/public/demandes-suivante'
    | '/api/public/lister-abonnes'
    | '/api/public/nettoyage-statut'
    | '/api/public/nettoyage-suivant'
    | '/api/public/publier-sources'
    | '/api/public/publier-synthese'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compte'
    | '/api/public/action-source-statut'
    | '/api/public/action-source-suivante'
    | '/api/public/demande-statut'
    | '/api/public/demandes-suivante'
    | '/api/public/lister-abonnes'
    | '/api/public/nettoyage-statut'
    | '/api/public/nettoyage-suivant'
    | '/api/public/publier-sources'
    | '/api/public/publier-synthese'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompteRoute: typeof CompteRoute
  ApiPublicActionSourceStatutRoute: typeof ApiPublicActionSourceStatutRoute
  ApiPublicActionSourceSuivanteRoute: typeof ApiPublicActionSourceSuivanteRoute
  ApiPublicDemandeStatutRoute: typeof ApiPublicDemandeStatutRoute
  ApiPublicDemandesSuivanteRoute: typeof ApiPublicDemandesSuivanteRoute
  ApiPublicListerAbonnesRoute: typeof ApiPublicListerAbonnesRoute
  ApiPublicNettoyageStatutRoute: typeof ApiPublicNettoyageStatutRoute
  ApiPublicNettoyageSuivantRoute: typeof ApiPublicNettoyageSuivantRoute
  ApiPublicPublierSourcesRoute: typeof ApiPublicPublierSourcesRoute
  ApiPublicPublierSyntheseRoute: typeof ApiPublicPublierSyntheseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/action-source-statut': {
      id: '/api/public/action-source-statut'
      path: '/api/public/action-source-statut'
      fullPath: '/api/public/action-source-statut'
      preLoaderRoute: typeof ApiPublicActionSourceStatutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/action-source-suivante': {
      id: '/api/public/action-source-suivante'
      path: '/api/public/action-source-suivante'
      fullPath: '/api/public/action-source-suivante'
      preLoaderRoute: typeof ApiPublicActionSourceSuivanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demande-statut': {
      id: '/api/public/demande-statut'
      path: '/api/public/demande-statut'
      fullPath: '/api/public/demande-statut'
      preLoaderRoute: typeof ApiPublicDemandeStatutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demandes-suivante': {
      id: '/api/public/demandes-suivante'
      path: '/api/public/demandes-suivante'
      fullPath: '/api/public/demandes-suivante'
      preLoaderRoute: typeof ApiPublicDemandesSuivanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lister-abonnes': {
      id: '/api/public/lister-abonnes'
      path: '/api/public/lister-abonnes'
      fullPath: '/api/public/lister-abonnes'
      preLoaderRoute: typeof ApiPublicListerAbonnesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nettoyage-statut': {
      id: '/api/public/nettoyage-statut'
      path: '/api/public/nettoyage-statut'
      fullPath: '/api/public/nettoyage-statut'
      preLoaderRoute: typeof ApiPublicNettoyageStatutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nettoyage-suivant': {
      id: '/api/public/nettoyage-suivant'
      path: '/api/public/nettoyage-suivant'
      fullPath: '/api/public/nettoyage-suivant'
      preLoaderRoute: typeof ApiPublicNettoyageSuivantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publier-sources': {
      id: '/api/public/publier-sources'
      path: '/api/public/publier-sources'
      fullPath: '/api/public/publier-sources'
      preLoaderRoute: typeof ApiPublicPublierSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publier-synthese': {
      id: '/api/public/publier-synthese'
      path: '/api/public/publier-synthese'
      fullPath: '/api/public/publier-synthese'
      preLoaderRoute: typeof ApiPublicPublierSyntheseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompteRoute: CompteRoute,
  ApiPublicActionSourceStatutRoute: ApiPublicActionSourceStatutRoute,
  ApiPublicActionSourceSuivanteRoute: ApiPublicActionSourceSuivanteRoute,
  ApiPublicDemandeStatutRoute: ApiPublicDemandeStatutRoute,
  ApiPublicDemandesSuivanteRoute: ApiPublicDemandesSuivanteRoute,
  ApiPublicListerAbonnesRoute: ApiPublicListerAbonnesRoute,
  ApiPublicNettoyageStatutRoute: ApiPublicNettoyageStatutRoute,
  ApiPublicNettoyageSuivantRoute: ApiPublicNettoyageSuivantRoute,
  ApiPublicPublierSourcesRoute: ApiPublicPublierSourcesRoute,
  ApiPublicPublierSyntheseRoute: ApiPublicPublierSyntheseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
